services:
  backend:
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - .env
    ports:
      - "80:3000"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-stack-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always