services:
  backend:
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - .env
    expose:
      - "8000"

  frontend:
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - .env
    ports:
      - "80:3000"
