version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
