version: "3.9"

services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/arm64
        - linux/amd64
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/arm64
        - linux/amd64
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    ports:
      - "80:3000"
    restart: always
