version: "3.9"

services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
        # - linux/arm64
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
        # - linux/arm64
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    ports:
      - "80:3000"
    restart: always
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=jbfiu23fb9d23d2323d2if4h
    command: ["redis-server", "--requirepass", "jbfiu23fb9d23d2323d2if4h"]
    restart: always