version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: biswalswaraj88/thesius-app:backend
    env_file:
      - ./.env
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
    image: biswalswaraj88/thesius-app:frontend
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    ports:
      - "80:3000"
    restart: always
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-stack-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always