dummy_papers = [
    {
        "paperId": "1a23b4c56d7e8f90123g4h567i8j9kl0m123n456",
        "url": "https://www.semanticscholar.org/paper/1a23b4c56d7e8f90123g4h567i8j9kl0m123n456",
        "title": "A Survey of Retrieval-Augmented Generation Models",
        "abstract": "This survey explores Retrieval-Augmented Generation (RAG) models, which combine information retrieval with generative models, discussing recent advances, architectures, and applications in knowledge-intensive NLP tasks.",
        "venue": "Conference on Neural Information Processing Systems",
        "year": 2021,
        "referenceCount": 112,
        "citationCount": 203,
        "influentialCitationCount": 51,
        "isOpenAccess": True,
        "openAccessPdf": {
            "url": "https://papers.nips.cc/2021/1234-survey-rag.pdf",
            "status": "OPEN_ACCESS",
        },
        "fieldsOfStudy": ["Computer Science", "Artificial Intelligence"],
        "tldr": {
            "model": "tldr@v2.0.0",
            "text": "Discusses advances in Retrieval-Augmented Generation (RAG) models for knowledge-intensive tasks, detailing architectures and performance.",
        },
    },
    {
        "paperId": "2b34c5d678ef90123g4h5i67j8kl0m1n234o5678",
        "url": "https://www.semanticscholar.org/paper/2b34c5d678ef90123g4h5i67j8kl0m1n234o5678",
        "title": "Retrieval-Augmented Generation for Conversational AI",
        "abstract": "This paper examines how retrieval-augmented generation enhances conversational AI, leveraging external documents to improve context-specific responses, and evaluates performance across datasets.",
        "venue": "Annual Conference of the Association for Computational Linguistics",
        "year": 2020,
        "referenceCount": 87,
        "citationCount": 129,
        "influentialCitationCount": 33,
        "isOpenAccess": True,
        "openAccessPdf": {
            "url": "https://aclweb.org/anthology/2020.acl-conv-ai.pdf",
            "status": "OPEN_ACCESS",
        },
        "fieldsOfStudy": ["Natural Language Processing", "Artificial Intelligence"],
        "tldr": {
            "model": "tldr@v2.0.0",
            "text": "Investigates RAG models in conversational AI, focusing on improved context-specific responses using document retrieval.",
        },
    },
    {
        "paperId": "3c45d6e789f0123g4h5i67j8kl9m0n123p45678q",
        "url": "https://www.semanticscholar.org/paper/3c45d6e789f0123g4h5i67j8kl9m0n123p45678q",
        "title": "Scaling Retrieval-Augmented Generation in Open-Domain QA",
        "abstract": "This study addresses challenges in scaling retrieval-augmented generation for open-domain question answering, proposing optimizations for high-volume data and evaluating retrieval effectiveness.",
        "venue": "International Conference on Machine Learning",
        "year": 2019,
        "referenceCount": 75,
        "citationCount": 168,
        "influentialCitationCount": 47,
        "isOpenAccess": False,
        "openAccessPdf": {
            "url": "https://icml.cc/2019/qa_rag_scaling.pdf",
            "status": "CLOSED_ACCESS",
        },
        "fieldsOfStudy": ["Machine Learning", "Information Retrieval"],
        "tldr": {
            "model": "tldr@v2.0.0",
            "text": "Proposes scaling techniques for RAG in open-domain QA, focusing on data handling and retrieval accuracy.",
        },
    },
    {
        "paperId": "4d56e7f8901g23h4i5j67kl8m9n01234p567890q",
        "url": "https://www.semanticscholar.org/paper/4d56e7f8901g23h4i5j67kl8m9n01234p567890q",
        "title": "Enhancing Document Retrieval for Generative Tasks in NLP",
        "abstract": "This research improves document retrieval within RAG models by introducing hierarchical indexing, boosting efficiency in generative tasks like summarization and QA.",
        "venue": "European Conference on Information Retrieval",
        "year": 2022,
        "referenceCount": 63,
        "citationCount": 87,
        "influentialCitationCount": 25,
        "isOpenAccess": True,
        "openAccessPdf": {
            "url": "https://ecir2022.org/hierarchical-rag.pdf",
            "status": "OPEN_ACCESS",
        },
        "fieldsOfStudy": ["Information Retrieval", "Natural Language Processing"],
        "tldr": {
            "model": "tldr@v2.0.0",
            "text": "Introduces hierarchical indexing for efficient document retrieval in RAG, aiding summarization and QA tasks.",
        },
    },
    {
        "paperId": "5e67f89012g34h5i67j8kl9m0n123456p78901qr",
        "url": "https://www.semanticscholar.org/paper/5e67f89012g34h5i67j8kl9m0n123456p78901qr",
        "title": "Cross-Lingual Retrieval-Augmented Generation for Low-Resource Languages",
        "abstract": "Explores how RAG models can be adapted for low-resource languages through cross-lingual retrieval, discussing language-specific challenges and potential solutions.",
        "venue": "Conference on Empirical Methods in Natural Language Processing",
        "year": 2023,
        "referenceCount": 98,
        "citationCount": 45,
        "influentialCitationCount": 18,
        "isOpenAccess": False,
        "openAccessPdf": {
            "url": "https://emnlp.org/2023/cross-lingual-rag.pdf",
            "status": "OPEN_ACCESS",
        },
        "fieldsOfStudy": ["Natural Language Processing", "Computational Linguistics"],
        "tldr": {
            "model": "tldr@v2.0.0",
            "text": "Discusses adapting RAG models for low-resource languages using cross-lingual retrieval, addressing language challenges.",
        },
    },
]

